def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.add_route('register', '/register')
    config.add_route('admin/consult', '/admin/consult')
    config.add_route('admin/consult_close', '/admin/consult_close')
    config.add_route('admin/card', '/admin/card')
    config.add_route('admin/card_close', '/admin/card_close')
    config.add_route('admin/credit', '/admin/credit')
    config.add_route('admin/close_credit', '/admin/close_credit')
    config.add_route('admin', '/admin')
